version: 2
workflows:
  version: 2
  build:
    jobs:
      - build-latest
      - build-1.12
  scheduled:
    triggers:
      - schedule:
          cron: "1 2 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-latest
      - build-1.12

jobs:
  build-latest: &build-template
    docker:
      - image: circleci/golang:latest

    environment:
      PATH: /tmp/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    steps:
      - run: uname -a
      - run: go version
      - run: sudo apt-get update
      - run: |
              sudo apt-get install -y libusb-1.0-0-dev
              sudo apt-get install -y libdbus-glib-1-dev
              sudo apt-get install -y libbluetooth-dev
              sudo apt-get install -y libnl-genl-3-dev
              sudo apt-get install -y libibverbs-dev
              sudo apt-get install -y libssl-dev
              sudo apt-get install -y libssl1.0.0
              sudo apt-get install -y libdnet-dev
              sudo apt-get install -y libsmi2-dev
              sudo apt-get install -y libcap-ng-dev
              sudo apt-get install -y libpcap-dev
      - run: |
              cd ..
              git clone --depth 3 --branch=master --quiet git://github.com/the-tcpdump-group/tcpdump.git
              cd tcpdump
              ./configure --prefix=/tmp
              make
              sudo make install
      - checkout
      - run: go vet ./...
      - run: go test -v ./...

  build-1.12:
    <<: *build-template
    docker:
      - image: circleci/golang:1.12
